import { Montserrat } from "next/font/google";
import "./globals.css";

import NavElement from "./components/navigation/desktop";
import MobileNav from "./components/navigation/mobile";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="hidden fixed bottom-0 mb-10 w-full sm:flex justify-center">
        <NavElement />
      </div>
      <div className="fixed w-full bottom-0 pb-8 m-0 flex justify-center sm:hidden">
        <MobileNav />
      </div>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
